#!/usr/bin/env bash

BASEDIR=$(builtin cd ..; pwd)

# ----------------------------------------------------------------
# DEFAULTS
# ----------------------------------------------------------------

NODE="stormeye2000/cspr-cctl:release-1.5.6"
BRANCH='main'

# ----------------------------------------------------------------
# INCLUDES
# ----------------------------------------------------------------

source inc/terminus-help
source inc/terminus-node
source inc/terminus-init
source inc/terminus-test

# ----------------------------------------------------------------
# ENTRY POINT
# ----------------------------------------------------------------

for ARGUMENT in "$@"
do
    CMD=$(echo "$ARGUMENT" | cut -f1 -d=)
    case "$CMD" in
        init)
           _docker
           _assets
           _init "$@"
           ;;
        help)
           _help
           ;;
        node)
          _docker "$@"
          _assets
          ;;
        test)
           _test
           ;;
        assets)
           _assets
           ;;
        *)
          echo 'Unrecognised command. Options are help, node, assets, init and test';;
    esac
done





