#!/usr/bin/env bash

CCTL_RELEASE="stormeye2000/cspr-cctl:release-1.5.6"
DOCKER_NAME="cspr-cctl"
BASEDIR=$(builtin cd ..; pwd)
CCTL_ASSETS=/home/cctl/cctl/assets

if ! [ -x "$(command -v docker)" ]; then
  echo 'Error: docker is not installed.' >&2
  exit 1
fi

if [ -n "$1" ]; then
  CCTL_RELEASE=$1
  echo "Using CCTL Docker image $CCTL_RELEASE"
else
  echo "No CCTL docker image provided, defaulting to $CCTL_RELEASE"
fi

echo "Stopping and removing any running image..."
docker ps -q --filter "name=$DOCKER_NAME" | grep -q . && docker stop $DOCKER_NAME && docker rm -fv $DOCKER_NAME > /dev/null 2>&1

echo "Starting image..."
docker run --rm -it --name $DOCKER_NAME -d -p 25101:25101 -p 11101:11101 -p 14101:14101 -p 18101:18101 $CCTL_RELEASE

echo "Waiting for node to start...."
sleep 10

echo "Copying node assets locally...."

# clear the assets folder
rm -rf  ${BASEDIR}/assets
mkdir ${BASEDIR}/assets
mkdir ${BASEDIR}/assets/net-1
mkdir ${BASEDIR}/assets/chainspec
mkdir ${BASEDIR}/assets/faucet
# copy net-1 users
docker cp cspr-cctl:$CCTL_ASSETS/users/. ${BASEDIR}/assets/net-1
# copy net-1 chainspec
docker cp cspr-cctl:$CCTL_ASSETS/genesis ${BASEDIR}/assets/net-1/chainspec
# copy faucet keys
docker cp cspr-cctl:$CCTL_ASSETS/faucet/ ${BASEDIR}/assets/net-1/faucet
