# This workflow will:
#   - download and start a NCTL docker image
#   - upload the nctl assets as a project artifact
#   - download the latest casper-java-sdk and build the jar
#   - upload the sdk jar as a project artifact
#   - download the test platform
#   - download the project artifacts and move to the required directories
#   - run the cucumber tests via gradle


name: CSPR Python SDK Standard Tests
on:
  workflow_dispatch:
jobs:
  build:
    name: Setting Up NCTL
    runs-on: ubuntu-latest
    services:
      storm-nctl:
        image: makesoftware/casper-nctl:latest
        options: --name storm-nctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '30sec'
        ports:
          - 11101:11101
          - 14101:14101
          - 18101:18101
    steps:
      # Build the assets folder from the started NCTL docker image
      - name: Preparing NCTL assets on the started NCTL docker image
        run: |
          echo "Wait for NCTL"
          sleep 30s
          mkdir assets
          docker cp storm-nctl:/home/casper/casper-node/utils/nctl/assets/net-1/chainspec assets
          docker cp storm-nctl:/home/casper/casper-node/utils/nctl/assets/net-1/users assets
          mv assets/users assets/net-1
          mv assets/chainspec assets/net-1/chainspec          

      # Upload the NCTL assets to a project artifact
      - name: Upload NCTL assets to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nctl-accounts
          path: |
            assets/net-1/chainspec/accounts.toml
            assets/net-1/user-*

      # Checkout the latest Casper Python SDK from their repo ready for a build
      - name: Checkout SDK source code
        uses: actions/checkout@v2
        with:
         repository: casper-network/casper-python-sdk
         ref: main
         path: casper-python-sdk

      # Upload the Python SDK source code artifact
      - name: Upload Python SDK code to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-sdk
          path: |
            casper-python-sdk/*


      # Download the NCTL assets artifact
      - name: Download NCTL assets artifact
        uses: actions/download-artifact@v3
        with:
          name: nctl-accounts

      # Download the python sdk artifact
      - name: Download python sdk artifact
        uses: actions/download-artifact@v3
        with:
          name: python-sdk

      # Checkout the test platform Python code
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Move the downloaded assets to their required folders
      # Run the actual cucumber tests
      - name: Copy artifacts and test with cucumber
        run: |
          ls -ltra
          cd casper-python-sdk
          sudo pip install -e .
          cd ..
          pip install -r requirements.txt
          pip install behave
          behave test/features --junit
