# This workflow will:
#   - download and start a NCTL docker image
#   - download the latest casper-python-sdk
#   - download the test platform
#   - run the cucumber tests via behave

name: CSPR Python SDK Standard Tests
on:
  workflow_dispatch:
jobs:
  build:
    name: Setting Up NCTL
    runs-on: ubuntu-latest
    services:
      nctl:
        image: stormeye2000/cspr-nctl:1.5
        options: --name cspr-nctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '30sec'
        ports:
          - 11101:11101
          - 14101:14101
          - 18101:18101
          - 25101:25101
    steps:
       # Start the NCTL docker image
      - name: Starting the NCTL docker image
        run: |
          echo "Wait for NCTL"
          sleep 30s        

      # Checkout the latest Casper Python SDK from their repo ready for a build
      - name: Checkout SDK source code
        uses: actions/checkout@v2
        with:
         repository: casper-network/casper-python-sdk
         ref: main
         path: casper-python-sdk

      # Checkout the test platform Python code
      - name: Checkout the test platform Python code
        uses: actions/checkout@v2
        with:
          path: cspr-standard-tests-python

      # Set up Python
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Run the actual cucumber tests
      - name: Test with cucumber
        run: |

          cd cspr-standard-tests-python/sh && 
          chmod +x docker-copy-assets.sh && 
          ./docker-copy-assets.sh && cd ../..  
          
          cd casper-python-sdk
          sudo pip install -e .

          cd ../cspr-standard-tests-python
          pip install -r requirements.txt
          pip install behave
          behave test/features --junit
